# Generated by Django 3.0.7 on 2021-05-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='openticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('oreceiver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oreceiver', to='live.Userprofile')),
                ('osender_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osender', to='live.Userprofile')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
