# Generated by Django 3.0.7 on 2021-05-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_auto_20210504_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeticket',
            name='creceiver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creceiver', to='live.Userprofile'),
        ),
        migrations.AlterField(
            model_name='closeticket',
            name='csender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csender', to='live.Userprofile'),
        ),
        migrations.AlterField(
            model_name='openticket',
            name='oreceiver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oreceiver', to='live.Userprofile'),
        ),
        migrations.AlterField(
            model_name='openticket',
            name='osender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osender', to='live.Userprofile'),
        ),
        migrations.DeleteModel(
            name='headprofile',
        ),
    ]
