# Generated by Django 3.0.7 on 2021-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_auto_20210504_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketprofile',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=42)),
            ],
        ),
    ]
