# Generated by Django 3.0.7 on 2021-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_ticketprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprofile',
            name='email',
            field=models.EmailField(default=123456789, max_length=254),
            preserve_default=False,
        ),
    ]
