# Generated by Django 3.0.7 on 2021-05-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_ticketprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
