# Generated by Django 3.0.7 on 2021-05-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_auto_20210505_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprofile',
            name='password',
            field=models.CharField(default=None, max_length=250,null=True),
        ),
        migrations.AlterField(
            model_name='ticketprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
