# Generated by Django 3.0.7 on 2021-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0012_auto_20210505_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='access',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
